SectionVerb {
	EnableSequence [
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 1"
		cset "name='MultiMedia3 Mixer TX_CODEC_DMA_TX_3' 1"
	]
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones Playback"
	Include.wcdhpe.File "/codecs/wcd938x/HeadphoneEnableSeq.conf"
	Include.wcdhpd.File "/codecs/wcd938x/HeadphoneDisableSeq.conf"
	Include.rxmhpe.File "/codecs/qcom-lpass/rx-macro/HeadphoneEnableSeq.conf"
	Include.rxmhpd.File "/codecs/qcom-lpass/rx-macro/HeadphoneDisableSeq.conf"
	Value {
		PlaybackChannels 2
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
	}
}

SectionDevice."Mic1" {
	Comment "Top Microphone"
	Include.wcdmice.File "/codecs/wcd938x/AnalogMic1EnableSeq.conf"
	Include.wcdmicd.File "/codecs/wcd938x/AnalogMic1DisableSeq.conf"
	Include.txmhpe.File "/codecs/qcom-lpass/tx-macro/SoundwireMic0EnableSeq.conf"
	Include.txmhpd.File "/codecs/qcom-lpass/tx-macro/SoundwireMicDisableSeq.conf"
	Value {
		CaptureChannels 1
		CapturePriority 200
		CapturePCM "hw:${CardId},2"
		CaptureMixer "default:${CardId}"
	}
}
